### PR TITLE
WIP - Changed API params to be unified

### PR DESCRIPTION
**Pull request by artmello**
- Used the same param names for target/source hosts/users
- Added API support to describe hosts and users for both target and
source
- Added API support to enable debug mode for each endpoint

### CODE REVIEW

**Comment by jmikovic** [comment]
- Debug is not an actor parameter therefore shouldn't be included in the params structs
- Added parameters are not used by the actors, no reason to have them in structs (check with the snactor repo)
- Actor definitions need to be updated as well

**Comment by artmello** [comment]
@jmikovic, thanks for reviewing! Idea here was to unify the parameters name/list for daemon API, but I am trying not to break nobody's workflow while updating that on the different repositories (leappctl, leapp-go and snactor). Since I was working with leappctl, I started by it with this [PR](https://github.com/leapp-to/leappctl/pull/2). With it I am renaming some params, like target-user-name to be target-user, adding some "missing" ones (not in fact missing, since they are working right now, but in the sense to have a pattern on the API), like target-user for actors that just request target-host, and adding a new one, like debug. Debug it was not used by no actors so far, but it was defined at migrate-machine leappctl, I think it could be a good improve to actors, but I am totally up to remove it. This current PR would not make leapp-go stop working, but could be a discussion and, if approved, define the changes that need to be applied at snactor relevant actors. This was based at "Task: API params naming unification" that is at etherpad by now. Let me know what do you think or if you prefer that we have a snactor PR first.

**Comment by jmikovic** [comment]
I looked at it again and I now understand why snactor PR is not necessary at the moment, but I still think this should be split into two PRs: one for unification of names and another one for adding new and "missing" params. Unification can go through and we can then discuss the changes to actors.

**Comment by jmikovic** [comment]
Update API documentation as well, please

**Comment by artmello** [comment]
In fact, I think you have a fair point here. I will first update snactor's actors and to do that move such discuss about existing input parameters to this future PR against it. If we reach an agreement and decide to really change actors I will update this PR (or split it in more than one). Until there will keep it as WIP.

**Comment by artmello** [comment]
Not sure if such a thing is still relevant, will close it and reopens if by any chance it become necessary again

**Pull request closed without merging**
